# Generated by Django 4.0.2 on 2022-04-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='contetn',
            new_name='content',
        ),
    ]
